// Mutations-types
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const USERINFO_SUCCESS = 'USERINFO_SUCCESS'
export const USERINFO_FAILURE = 'USERINFO_FAILURE'
export const LOGOUT_USER = 'LOGOUT_USER'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'

export const CHANGE_STYLE_MODE = 'CHANGE_STYLE_MODE'
export const GET_INDEX_IMG = 'GET_INDEX_IMG'
export const GET_CAPTCHAURL = 'GET_CAPTCHAURL'

export const SUCCESS_GET_SNSLOGINS = 'SUCCESS_GET_SNSLOGINS'
export const FAILURE_GET_SNSLOGINS = 'FAILURE_GET_SNSLOGINS'

export const GET_CAMERA_LIST_SUCCESS = 'GET_CAMERA_LIST_SUCCESS'
export const GET_CAMERA_LIST_FAILURE = 'GET_CAMERA_LIST_FAILURE'

export const CHANGE_VIDEO_OPTIONS = 'CHANGE_VIDEO_OPTIONS'
export const CHANGE_TASK_OPTIONS = 'CHANGE_TASK_OPTIONS'

export const VIDEO_LIST = 'VIDEO_LIST'
export const VIDEO_DETAIL = 'VIDEO_DETAIL'
export const ADD_VIDEO_LIST = 'ADD_VIDEO_LIST'
export const REQUEST_VIDEO_LIST = 'REQUEST_VIDEO_LIST'
export const GET_VIDEO_LIST_FAILURE = 'GET_VIDEO_LIST_FAILURE'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'

export const VIDEO_TASK_LIST = 'VIDEO_TASK_LIST'
export const REQUEST_VIDEO_TASK_LIST = 'REQUEST_VIDEO_TASK_LIST'
export const ADD_VIDEO_TASK_LIST = 'ADD_VIDEO_TASK_LIST'
export const GET_VIDEO_TASK_LIST_FAILURE = 'GET_VIDEO_TASK_LIST_FAILURE'
